apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.server }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}
    solvers:
    - dns01:
        route53:
          region: {{ .Values.region }}
          hostedZoneID: {{ .Values.hostedZoneID }}
          role: {{ .Values.role }}
          accessKeyID: {{ .Values.accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretRef }}
            key: {{ .Values.secretKeyRef }}
