apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: csi-credentials
    namespace: {{ .Release.Namespace }}
  type: Opaque
  stringData: &data
    cloudFolderID: {{ .Values.folderID }}
    serviceAccountJSON: |
      {
        "id": {{ .Values.serviceAccount.keyID | quote }},
        "service_account_id": {{ .Values.serviceAccount.id | quote }},
        "created_at": {{ .Values.serviceAccount.createdAt }},
        "key_algorithm": {{ .Values.serviceAccount.keyAlgorithm | quote }},
        "public_key": {{ .Values.serviceAccount.publicKey | quote }},
        "private_key": {{ .Values.serviceAccount.privateKey | quote }}
      }
- apiVersion: v1
  kind: Secret
  metadata:
    name: csi-credentials
    namespace: kube-system
  type: Opaque
  stringData:
    <<: *data
