apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: csi-credentials
  type: Opaque
  stringData: &data
    cloudFolderID: {{ .Values.folderID }}
    serviceAccountJSON: |
      {
        "id": "{{ .Values.serviceAccount.keyID }}",
        "service_account_id": "{{ .Values.serviceAccount.id }}",
        "created_at": "{{ .Values.serviceAccount.createdAt }}",
        "key_algorithm": "{{ .Values.serviceAccount.keyAlgorithm }}",
        "public_key": "{{ .Values.serviceAccount.publicKey }}",
        "private_key": "{{ .Values.serviceAccount.privateKey }}"
      }
- apiVersion: v1
  kind: Secret
  metadata:
    name: csi-credentials
    namespace: kube-system
  type: Opaque
  stringData:
    <<: *data
