---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: network-hdd
  namespace: {{ .Release.Namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: yandex.csi.flant.com
parameters:
  typeID: network-hdd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: network-ssd
  namespace: {{ .Release.Namespace }}
provisioner: yandex.csi.flant.com
parameters:
  typeID: network-ssd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
