apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.secretName }}
  dnsNames:
  {{- range .Values.dnsNames }}
  - {{ . }}
  {{- end }}
  {{- if .Values.uriSANs }}
  uriSANs:
  {{- range .Values.uriSANs }}
  - {{ . }}
  {{- end }}
  {{- end }}
  issuerRef:
    name: {{ .Values.issuerRef }}
    kind: {{ .Values.issuerKind }}
    group: cert-manager.io
